### ISSUE TITLE
Main js

### ISSUE THREAD

**Issue by lboyze** [Raccoon254/Aviator-Automated-Betika-Bot#2]
I got the following error

```
(node:30968) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Users\USER\Documents\scripts\Aviator-Automated-Betika-Bot-main\Aviator-Automated-Betika-Bot-main\package.json' of 'main.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was create
```
Which file should be the main.js?
**NB**
- Discussions is not enabled in this repo
- If I replace `main.js` with `mozzart.js` it runs, allows me to login but exits after some seconds. Should I have some cash in betting account before I run this :) ?
- If possible please show the outcome one is supposed to see

**Comment by Raccoon254** [comment]
sure should, these are real world implementations, you can run index.js for a free test
