### ISSUE TITLE
Request: Adapting Bot for Betika’s Live Aviator Game

### ISSUE THREAD

**Issue by eric-ricky** [Raccoon254/Aviator-Automated-Betika-Bot#5]
Hi, 
How do I adapt the bot to work on the live Aviator game embedded on Betika’s platform. On Betika’s website, the Aviator game runs inside an iframe, and this introduces cross-origin restrictions.

Thank you for creating such a great tool. I've tested it out on the fun mode, its great 👍

Any help would be greatly appreciated

**Comment by Raccoon254** [comment]
Hello, please message me on whatsapp
https://wa.link/w1774n
